### ISSUE TITLE
windows path issue with elsamuko-national-geographic-batch

### ISSUE THREAD

**Issue by m1d1** [elsamuko/gimp-elsamuko#1]
On linux, running the command

`gimp-console -n -i -b '(elsamuko-national-geographic-batch "/foo/bar/img.png" 60 1 60 25 0.4 1 0)' -b '(gimp-quit 0)'`

works just fine. 

My problem is to make this work on a windows based machine. 
I'm not sure if it really is an issue of the plugin-script or a GIMP related issue:

`C:\Program Files\GIMP 2\bin\gimp-console-2.8.exe -n -i -b "(elsamuko-national-geographic-batch "C:/Users/foo/AppData/Roaming/images/img.png" 60 1 60 25 0.4 1 0)" -b "(gimp-quit 0)"`

doesn't work.

Things I tried and didn't help:
- change the pwd to the directory containing the image-file and just give the filename "img.png"
- tried backslashes and double backslashes in filepath (`C:\Users\foo\...` and `C:\\Users\\foo\\...`)
- tried slashes and double slashes in filepath (`C:/Users/foo/...` and `C://Users//foo//...`)
- tried escaped slashes (`C:\/Users\/foo\/...`)
- tried to use ENV vars for filepath like (`%TEMP%/img.png`)

The only file argument that did work was `c:/img.jpg` but the root path is UAC protected and can't be used without admin rights.

Any ideas?

Thanks - Danke
-Michael

**Comment by elsamuko** [comment]
It works, if you escape path and quotes in the call:
`"C:\Program Files\GIMP 2\bin\gimp-console-2.8.exe" -n -i -b "(elsamuko-national-geographic-batch \"C:\\cygwin64\\home\\samuel_cyg\\projects\\gimp\\image.jpg\" 60 1 60 25 0.4 1 0)" -b "(gimp-quit 0)"`

Or you can navigate to the folder with your batch script and call it only with image.jpg:
`cd "C:\cygwin64\home\samuel_cyg\projects\gimp\"
"C:\Program Files\GIMP 2\bin\gimp-console-2.8.exe" -n -i -b "(elsamuko-national-geographic-batch \"image.jpg\" 60 1 60 25 0.4 1 0)" -b "(gimp-quit 0)"`

You can see, which pattern is used by GIMP, if you add
`(gimp-message (string-append "running elsamuko-national-geographic-batch " pattern))`
after the `(define (elsamuko-national-geographic-batch` block.

Source: https://superuser.com/a/537492
