### ISSUE TITLE
Face detection plugin?

### ISSUE THREAD

**Issue by moshpirit** [elsamuko/gimp-elsamuko#5]
Hi there! I am very curious about your plugins, especially the face detection one, but it doesn't seem to be published on GitHub, although it appears on your website. Is it no longer available for some incompatibility? Cause I'd like to try it :)

**Comment by elsamuko** [comment]
Hm, not so easy, the old (2010!) plugin was in plain C and used the now deprecated C API from OpenCV.  
And it's using the old GIMP plugin API.

**Comment by moshpirit** [comment]
I see… what a pity! thanks anyway!
