### ISSUE TITLE
Error: unbound variable plug-in-scatter-hsv

### ISSUE THREAD

**Issue by swannty** [elsamuko/gimp-elsamuko#7]
Those scripts should use `plug-in-hsv-noise` instead of `plug-in-scatter-hsv` to avoid following error: "unbound variable plug-in-scatter-hsv".

- elsamuko-grain.scm
- elsamuko-lomo.scm
- elsamuko-lomo-batch.scm
- elsamuko-movie-300.scm

_GIMP 2.10.34_
_Debian 12.6_

**Comment by elsamuko** [comment]
Hi @swannty,

the scripts in the debian package may be too old, the current main branch already uses `plug-in-hsv-noise`:
https://github.com/elsamuko/gimp-elsamuko/commit/1800afafab085dff2866b7f44580f04e27faaf22

Regards,
Samuel
